name: ZPort
main: com.zeeveener.zport.ZPort
author: zeeveener
version: 0.0.1-ALPHA
description: Teleportation Suite for Bukkit
commands:
    zsetwarp:
        aliases: [setwarp, sw, zsw]
        usage: /<command> (name) (private)
    zremwarp:
        aliases: [remwarp, delwarp, zrw, zdw, rw, dw]
        usage: /<command> (warp)
    zwarp:
        aliases: [warp, zw, w]
        usage: /<command> (warp)
    zsethome:
        aliases: [sethome, sh, zsh]
        usage: /<command>
    zhome:
        aliases: [home, h, zh]
        usage: /<command> (world)
    ztp:
        aliases: [tp]
        usage: /<command> (player)
    ztphere:
        aliases: [tphere, tph, ztph]
        usage: /<command> (player)
    ztpto:
        aliases: [tpto]
        usage: /<command> (x) (y) (z) (world)
    zback:
        aliases: [back, b, zb]
        usage: /<command>
    zpset:
        aliases: [zps]
        usage: /<command> [toggle] (value) (options)
permissions:
    zp.set:
        description: Allows usage of all setting altering commands
        children:
            zp.set.toggle: true
            zp.set.cooldown: true
    zp.set.cooldown:
        description: Change the value of all Cooldowns
        children:
            zp.set.cooldown.warp: true
            zp.set.cooldown.tele: true
            zp.set.cooldown.home: true
            zp.set.cooldown.back: true
    zp.set.cooldown.home:
        description: Change the cooldown period for going home
    zp.set.cooldown.warp:
        description: Change the cooldown period for warping
    zp.set.cooldown.tele:
        description: Change the cooldown period for teleportation
    zp.set.cooldown.back:
        description: Change the cooldown period for going back
    zp.set.warmup:
        description: Change the value of all Warmups
        children:
            zp.set.warmup.warp: true
            zp.set.warmup.tele: true
            zp.set.warmup.home: true
            zp.set.warmup.back: true
    zp.set.warmup.home:
        description: Change the warmup period for going home
    zp.set.warmup.warp:
        description: Change the warmup period for warping
    zp.set.warmup.tele:
        description: Change the warmup period for teleportation
    zp.set.warmup.back:
        description: Change the warmup period for going back
    zp.set.toggle:
        description: Toggle all major features in game
        children:
            zp.set.toggle.warp: true
            zp.set.toggle.home: true
            zp.set.toggle.sign: true
            zp.set.toggle.tele: true
    zp.set.toggle.warp:
        description: Toggle the Warping feature
    zp.set.toggle.home:
        description: Toggle the Home feature
    zp.set.toggle.tele:
        description: Toggle the Teleportation feature
    zp.set.toggle.sign:
        description: Toggle the WarpSign feature
    zp.exempt:
        description: Exempt from all limitations and stops (Does not include command permissions)
        children:
            zp.exempt.warmups: true
            zp.exempt.cooldowns: true
            zp.exempt.tpblocks: true
            zp.exempt.toggles: true
    zp.exempt.toggles:
        description: Can use features even if disabled
        children:
            zp.exempt.toggles.warp: true
            zp.exempt.toggles.sign: true
            zp.exempt.toggles.tele: true
            zp.exempt.toggles.home: true
    zp.exempt.toggles.warp:
        description: Allow usage of warps even when they are disabled
    zp.exempt.toggles.home:
        description: Allow usage of homes even when they are disabled
    zp.exempt.toggles.tele:
        description: Allow usage of teleportation even when it is disabled
    zp.exempt.toggles.sign:
        description: Allow usage of warpsigns even when they are disabled
    zp.exempt.tpblocks:
        description: Teleport without being stopped by tpblocks.
    zp.exempt.warmups:
        description: Teleport/Warp/Home/Back without waiting first.
    zp.exempt.cooldowns:
        description: Teleport/Warp/Home/Back immediately after doing so.
    zp.tp:
        description: Allow all teleportation features
        children:
            zp.tp.to: true
            zp.tp.here: true
            zp.tp.back: true
    zp.tp.back:
        description: Return to a previous location
    zp.tp.to:
        description: Allow players to teleport to all targets
        children:
            zp.tp.to.player: true
            zp.tp.to.op: true
            zp.tp.to.coord: true
    zp.tp.here:
        description: Allow players to teleport targets to themselves
        children:
            zp.tp.here.player: true
            zp.tp.here.op: true
    zp.tp.to.player: 
        description: Teleport to other players
    zp.tp.to.coord:
        description: Teleport to coordinates
    zp.tp.to.op:
        description: Teleport to ops
    zp.tp.here.player:
        description: Teleport players to yourself.
    zp.tp.here.op:
        description: Teleport ops to yourself
    zp.home:
        description: Allow usage and setting of homes
        children: 
            zp.home.use: true
            zp.home.set: true
    zp.home.use:
        description: Teleport to home FROM the world this permission is set for
    zp.home.set:
        description: Set the location of the home in the player's current world
    zp.warpsign:
        description: Allow all WarpSign features
        children:
            zp.warpsign.create: true
            zp.warpsign.destroy: true
            zp.warpsign.use: true
    zp.warpsign.create:
        description: Allows all WarpSign creation features
        children:
            zp.warpsign.create.public: true
            zp.warpsign.create.private: true
    zp.warpsign.create.public:
        description: Create public warpsigns
    zp.warpsign.create.private:
        description: Create private warpsigns
    zp.warpsign.destroy:
        description: Destroy all types of WarpSigns
        children:
            zp.warpsign.destroy.own: true
            zp.warpsign.destroy.others: true
    zp.warpsign.destroy.own:
        description: Destroy all of your own warpsigns
        children:
            zp.warpsign.destroy.own.public: true
            zp.warpsign.destroy.own.private: true
    zp.warpsign.destroy.own.private:
        description: Destroy your own private warpsigns
    zp.warpsign.destroy.own.public:
        description: Destroy your own public warpsigns
    zp.warpsign.destroy.others:
        description: Destroy other players warpsigns
        children:
            zp.warpsign.destroy.others.private: true
            zp.warpsign.destroy.others.public: true
    zp.warpsign.destroy.others.private:
        description: Destroy other players' private warpsigns
    zp.warpsign.destroy.others.public:
        description: Destroy other players' public warpsigns
    zp.warpsign.use:
        description: Use all types of WarpSigns
        children:
            zp.warpsign.use.own: true
            zp.warpsign.use.others: true
    zp.warpsign.use.own:
        description: Use all of your own warpsigns
        children:
            zp.warpsign.use.own.public: true
            zp.warpsign.use.own.private: true
    zp.warpsign.use.own.private:
        description: Use your own private warpsigns
    zp.warpsign.use.own.public:
        description: Use your own public warpsigns
    zp.warpsign.use.others:
        description: Use other players warpsigns
        children:
            zp.warpsign.use.others.private: true
            zp.warpsign.use.others.public: true
    zp.warpsign.use.others.private:
        description: Use other players' private warpsigns
    zp.warpsign.use.others.public:
        description: Use other players' public warpsigns
    zp.warp:
        description: Allows all warping features
        children:
            zp.warp.modify: true
            zp.warp.create: true
            zp.warp.destroy: true
            zp.warp.use: true
    zp.warp.modify:
        description: Allows all warp modification features
        children:
            zp.warp.modify.own: true
            zp.warp.modify.others: true
    zp.warp.modify.own:
        description: Allows modification of all of own warps
        children:
            zp.warp.modify.own.public: true
            zp.warp.modify.own.private: true
    zp.warp.modify.others:
        description: Allows modification of all of everyone else's warps
        children:
            zp.warp.modify.others.public: true
            zp.warp.modify.others.private: true
    zp.warp.create:
        description: Allows all warp creation features
        children:
            zp.warp.create.private: true
            zp.warp.create.public: true
    zp.warp.destroy:
        description: Allows all warp destruction features
        children:
            zp.warp.destroy.others: true
            zp.warp.destroy.own: true
    zp.warp.destroy.others:
        description: Allows destruction of other players private/public warps
        children:
            zp.warp.destroy.others.private: true
            zp.warp.destroy.others.public: true
    zp.warp.destroy.own:
        description: Allows destruction of own private/public warps
        children:
            zp.warp.destroy.own.private: true
            zp.warp.destroy.own.public: true
    zp.warp.use:
        description: Allows use of all warps
        children:
            zp.warp.use.own: true
            zp.warp.use.others: true
    zp.warp.use.own:
        description: Allows use of all your own warps
        children:
            zp.warp.use.own.private: true
            zp.warp.use.own.public: true
    zp.warp.use.others:
        description: Allows use of all of everyone else's private/public warps
        children:
            zp.warp.use.others.public: true
            zp.warp.use.others.private: true
    zp.warp.modify.own.public:
        description: Modify one's own public warps
    zp.warp.modify.own.private:
        description: Modify one's own private warps
    zp.warp.modify.others.public:
        description: Modify everyone else's public warps
    zp.warp.modify.others.private:
        description: Modify everyone else's private warps
    zp.warp.create.private:
        description: Create private warps
    zp.warp.create.public:
        description: Create public warps
    zp.warp.destroy.own.public:
        description: Destroy one's own public warps
    zp.warp.destroy.own.private:
        description: Destroy one's own private warps
    zp.warp.destroy.others.private:
        description: Destroy everyone else's private warps
    zp.warp.destroy.others.public:
        description: Destroy everyone else's public warps
    zp.warp.use.own.public:
        description: Use one's own public warps
    zp.warp.use.own.private:
        description: Use one's own private warps
    zp.warp.use.others.public:
        description: Use everyone else's public warps
    zp.warp.use.others.private:
        description: Use everyone else's private warps
    